services:
  - type: web
    name: backstage
    env: docker
    rootDirectory: apps/backstage
    repo: https://github.com/Stefs-Startup/monorepo # This is ignored on automated push but good practice
    region: oregon
    plan: free
